### PR TITLE
fix(Minting): show correct APR for curve after a sucessful mint

### LINKED ISSUE #296: Fix hardcoded APR of curve.fi sUSD on mint success
The current APR on the success card after minting is hard coded and must be replaced to reflect the live value represented in the /earn page

image

### PR DESCRIPTION
**Pull request by evgenyboxer**
Fixes #296

Currently, the link goes to back `/earn` - need to clarify if this should go to https://www.curve.fi/susdv2/ instead?

### CODE REVIEW

**Review by andytcf — APPROVED** [review]

File: sections/staking/components/TxSent/ActionCompleted.tsx [hunk 1]
```diff
@@ -50,6 +60,7 @@ const ActionCompleted: React.FC<ActionCompletedProps> = ({
 }) => {
 	const { t } = useTranslation();
 	const { push } = useRouter();
+	const lpData = useLPData();
 	const { etherscanInstance } = Etherscan.useContainer();
 	const link = etherscanInstance != null ? etherscanInstance.txLink(hash ?? '') : undefined;
```
Comment (andytcf) [inline sections/staking/components/TxSent/ActionCompleted.tsx:65]: @evgenyboxer link it to curve.fi

**Review by andytcf — CHANGES_REQUESTED** [review]
link externally to https://www.curve.fi/susdv2/

**Comment by evgenyboxer** [comment]
@andytcf fixed
